spring :   
  profiles:
    active: pro    
  application:
    name: ly-skill-dev     
  mvc: 
    throw-exception-if-no-handler-found : true 
  http:
    encoding:
     charset: UTF-8
    multipart:
     maxFileSize: 50Mb
     maxRequestSize: 100Mb  
          
server : 
  port : 7001 
  tomcat : 
   uri-encoding : UTF-8
   
#mybatis配置       
mybatis-plus: 
  typeAliasesPackage : com.ly.skill.entity.*
  mapperLocations : classpath:mapper/*/*Mapper.xml
    # 原生配置
  configuration:
    #auto-mapping-behavior: FULL
    map-underscore-to-camel-case: true
    cache-enabled: false  
    jdbcTypeForNull: null
 
  global-config:
      # 数据库相关配置
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 3
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: 1
    refresh-mapper: true
     
logging:
   level:
       com.ly.mssp.mapper: DEBUG       

    